# Introducing the Data

In [114]:
#https://www.kaggle.com/datasets/CooperUnion/cardataset
#Code written by Olivia M. Forrester

In [1]:
import pandas as pd

In [2]:
car = pd.read_csv('used_cars.csv')
car.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

## Characteristics and Features

In [3]:
import numpy as np

In [4]:
car

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [5]:
car.describe()

Year    Engine HP  Engine Cylinders  Number of Doors  \
count  11914.000000  11845.00000      11884.000000     11908.000000   
mean    2010.384338    249.38607          5.628829         3.436093   
std        7.579740    109.19187          1.780559         0.881315   
min     1990.000000     55.00000          0.000000         2.000000   
25%     2007.000000    170.00000          4.000000         2.000000   
50%     2015.000000    227.00000          6.000000         4.000000   
75%     2016.000000    300.00000          6.000000         4.000000   
max     2017.000000   1001.00000         16.000000         4.000000   

        highway MPG      city mpg    Popularity          MSRP  
count  11914.000000  11914.000000  11914.000000  1.191400e+04  
mean      26.637485     19.733255   1554.911197  4.059474e+04  
std        8.863001      8.987798   1441.855347  6.010910e+04  
min       12.000000      7.000000      2.000000  2.000000e+03  
25%       22.000000     16.000000    549.000000  2.100000e+04  
50%       26.000000     18.000000   1385.000000  2.999500e+04  
75%       30.000000     22.000000   2009.000000  4.223125e+04  
max      354.000000    137.000000   5657.000000  2.065902e+06

In [6]:
car.median()

C:\Users\jchac_vjlwe8u\AppData\Local\Temp\ipykernel_2176\961299306.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  car.median()


Year                 2015.0
Engine HP             227.0
Engine Cylinders        6.0
Number of Doors         4.0
highway MPG            26.0
city mpg               18.0
Popularity           1385.0
MSRP                29995.0
dtype: float64

In [7]:
car.mode()

Make           Model  Year  Engine Fuel Type  Engine HP  \
0  Chevrolet  Silverado 1500  2015  regular unleaded      200.0   

   Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0               4.0         AUTOMATIC  front wheel drive              4.0   

  Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
0       Crossover      Compact         Sedan           24        17   

   Popularity  MSRP  
0        1385  2000

In [8]:
car.var()

C:\Users\jchac_vjlwe8u\AppData\Local\Temp\ipykernel_2176\1087542622.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  car.var()


Year                5.745246e+01
Engine HP           1.192286e+04
Engine Cylinders    3.170392e+00
Number of Doors     7.767168e-01
highway MPG         7.855278e+01
city mpg            8.078052e+01
Popularity          2.078947e+06
MSRP                3.613104e+09
dtype: float64

In [9]:
car.skew()
#Positive skew: Highway MPG, City MPG, MSRP
#Negative skew: Year
#little skew: Engine HP, Engline Cylinders, Number of doors, Popularity

C:\Users\jchac_vjlwe8u\AppData\Local\Temp\ipykernel_2176\2261863883.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  car.skew()


Year                -1.221981
Engine HP            1.291230
Engine Cylinders     0.964542
Number of Doors     -0.968671
highway MPG          7.573931
city mpg             7.106681
Popularity           1.653443
MSRP                11.771987
dtype: float64

## Target Variable: MSRP

# Data Cleaning and Preprocessing

In [10]:
car.info()
#there are a total of 11914 rows but: 
#'Engine Fuel Type' shows 11911 
#'Engine HP' shows 11845
#'Engine Cylinders' shows 11884
#'Number of Doors' shows 11908
#'Market Category' shows 8172

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

## Dropping Useless Columns

In [11]:
cols = [ 'Model', 'Market Category']
car = car.drop(cols, axis=1)

In [12]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Year               11914 non-null  int64  
 2   Engine Fuel Type   11911 non-null  object 
 3   Engine HP          11845 non-null  float64
 4   Engine Cylinders   11884 non-null  float64
 5   Transmission Type  11914 non-null  object 
 6   Driven_Wheels      11914 non-null  object 
 7   Number of Doors    11908 non-null  float64
 8   Vehicle Size       11914 non-null  object 
 9   Vehicle Style      11914 non-null  object 
 10  highway MPG        11914 non-null  int64  
 11  city mpg           11914 non-null  int64  
 12  Popularity         11914 non-null  int64  
 13  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5), object(6)
memory usage: 1.3+ MB


## Filling Missing Values

In [13]:
print('Missing Engine Fuel Type count:',car['Engine Fuel Type'].isna().sum())
print('Missing Engine HP count:',car['Engine HP'].isna().sum())
print('Missing Engine Cylinders count:',car['Engine Cylinders'].isna().sum())
print('Missing Number of Doors count:',car['Number of Doors'].isna().sum())

Missing Engine Fuel Type count: 3
Missing Engine HP count: 69
Missing Engine Cylinders count: 30
Missing Number of Doors count: 6


In [14]:
#Enginge fuel type
car.fillna(value={'Engine Fuel Type':car['Engine Fuel Type'].mode()[0]},
               inplace=True)

In [15]:
#Engine HP
car.fillna(value={'Engine HP':car['Engine HP'].mean()},inplace=True)

In [16]:
#engine cylinders
car.fillna(value={'Engine Cylinders':car['Engine Cylinders'].mean()},
               inplace=True)

In [17]:
#number of doors
car.fillna(value={'Number of Doors':car['Number of Doors'].mode()[0]},
               inplace=True)

In [18]:
#check
car.isna().sum()>0

Make                 False
Year                 False
Engine Fuel Type     False
Engine HP            False
Engine Cylinders     False
Transmission Type    False
Driven_Wheels        False
Number of Doors      False
Vehicle Size         False
Vehicle Style        False
highway MPG          False
city mpg             False
Popularity           False
MSRP                 False
dtype: bool

## Encoding Categorical Variables

In [19]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Year               11914 non-null  int64  
 2   Engine Fuel Type   11914 non-null  object 
 3   Engine HP          11914 non-null  float64
 4   Engine Cylinders   11914 non-null  float64
 5   Transmission Type  11914 non-null  object 
 6   Driven_Wheels      11914 non-null  object 
 7   Number of Doors    11914 non-null  float64
 8   Vehicle Size       11914 non-null  object 
 9   Vehicle Style      11914 non-null  object 
 10  highway MPG        11914 non-null  int64  
 11  city mpg           11914 non-null  int64  
 12  Popularity         11914 non-null  int64  
 13  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5), object(6)
memory usage: 1.3+ MB


In [20]:
car_dummies = pd.get_dummies(car)
#dummies: Make, Engine Fuel Type, Transmission Type, Driven_Wheels, Vehicle Size, Vehicle Style 

In [21]:
car_dummies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 94 columns):
 #   Column                                                         Non-Null Count  Dtype  
---  ------                                                         --------------  -----  
 0   Year                                                           11914 non-null  int64  
 1   Engine HP                                                      11914 non-null  float64
 2   Engine Cylinders                                               11914 non-null  float64
 3   Number of Doors                                                11914 non-null  float64
 4   highway MPG                                                    11914 non-null  int64  
 5   city mpg                                                       11914 non-null  int64  
 6   Popularity                                                     11914 non-null  int64  
 7   MSRP                                                      

In [22]:
car_dummies.drop_duplicates(inplace=True)

# Descriptive Analysis

In [23]:
cols = ['MSRP']
car_dummies = car_dummies[cols + [c for c in car_dummies.columns if c not in cols]]

In [24]:
car_dummies.describe()

MSRP          Year     Engine HP  Engine Cylinders  \
count  1.118500e+04  11185.000000  11185.000000      11185.000000   
mean   4.196542e+04   2010.729012    253.418206          5.665075   
std    6.156164e+04      7.212749    109.850274          1.794834   
min    2.000000e+03   1990.000000     55.000000          0.000000   
25%    2.161000e+04   2007.000000    172.000000          4.000000   
50%    3.069500e+04   2015.000000    240.000000          6.000000   
75%    4.305000e+04   2016.000000    303.000000          6.000000   
max    2.065902e+06   2017.000000   1001.000000         16.000000   

       Number of Doors   highway MPG      city mpg    Popularity  \
count     11185.000000  11185.000000  11185.000000  11185.000000   
mean          3.454984     26.614126     19.735628   1558.218149   
std           0.872484      8.980041      9.181601   1445.797095   
min           2.000000     12.000000      7.000000      2.000000   
25%           2.000000     22.000000     16.000000    549.000000   
50%           4.000000     25.000000     18.000000   1385.000000   
75%           4.000000     30.000000     22.000000   2009.000000   
max           4.000000    354.000000    137.000000   5657.000000   

         Make_Acura  Make_Alfa Romeo  ...  Vehicle Style_Convertible  \
count  11185.000000     11185.000000  ...               11185.000000   
mean       0.021994         0.000447  ...                   0.066249   
std        0.146669         0.021139  ...                   0.248729   
min        0.000000         0.000000  ...                   0.000000   
25%        0.000000         0.000000  ...                   0.000000   
50%        0.000000         0.000000  ...                   0.000000   
75%        0.000000         0.000000  ...                   0.000000   
max        1.000000         1.000000  ...                   1.000000   

       Vehicle Style_Convertible SUV  Vehicle Style_Coupe  \
count                   11185.000000         11185.000000   
mean                        0.002503             0.105051   
std                         0.049973             0.306633   
min                         0.000000             0.000000   
25%                         0.000000             0.000000   
50%                         0.000000             0.000000   
75%                         0.000000             0.000000   
max                         1.000000             1.000000   

       Vehicle Style_Crew Cab Pickup  Vehicle Style_Extended Cab Pickup  \
count                   11185.000000                       11185.000000   
mean                        0.058471                           0.053017   
std                         0.234643                           0.224078   
min                         0.000000                           0.000000   
25%                         0.000000                           0.000000   
50%                         0.000000                           0.000000   
75%                         0.000000                           0.000000   
max                         1.000000                           1.000000   

       Vehicle Style_Passenger Minivan  Vehicle Style_Passenger Van  \
count                     11185.000000                 11185.000000   
mean                          0.034779                     0.010818   
std                           0.183227                     0.103450   
min                           0.000000                     0.000000   
25%                           0.000000                     0.000000   
50%                           0.000000                     0.000000   
75%                           0.000000                     0.000000   
max                           1.000000                     1.000000   

       Vehicle Style_Regular Cab Pickup  Vehicle Style_Sedan  \
count                      11185.000000         11185.000000   
mean                           0.030845             0.253643   
std                            0.172905             0.435115   
min      

# Main Analysis

## Problem Type: Regression

### features and target sets

In [25]:
X = car_dummies.iloc[:,1:] 
Y = car_dummies['MSRP']

In [26]:
#check
print(X.info())
print(Y.head(1))

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11185 entries, 0 to 11913
Data columns (total 93 columns):
 #   Column                                                         Non-Null Count  Dtype  
---  ------                                                         --------------  -----  
 0   Year                                                           11185 non-null  int64  
 1   Engine HP                                                      11185 non-null  float64
 2   Engine Cylinders                                               11185 non-null  float64
 3   Number of Doors                                                11185 non-null  float64
 4   highway MPG                                                    11185 non-null  int64  
 5   city mpg                                                       11185 non-null  int64  
 6   Popularity                                                     11185 non-null  int64  
 7   Make_Acura                                                

### train test split: 80/20

In [27]:
from sklearn.model_selection import train_test_split

In [37]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,
                                                 test_size=.2,
                                                 random_state=0)

In [38]:
print(car_dummies.shape)
print(X.shape)
print(X_train.shape)
print(X_test.shape)
print(Y.shape)
print(Y_train.shape)
print(Y_test.shape)

(11185, 94)
(11185, 93)
(8948, 93)
(2237, 93)
(11185,)
(8948,)
(2237,)


# Knn Regression

In [39]:
from sklearn.neighbors import KNeighborsRegressor

In [40]:
#define the model
knn_reg3 = KNeighborsRegressor(n_neighbors=3)
knn_reg4 = KNeighborsRegressor(n_neighbors=4)
knn_reg5 = KNeighborsRegressor(n_neighbors=5)
knn_reg35 = KNeighborsRegressor(n_neighbors=35)
#fitting/training the model
knn_reg3.fit(X_train,Y_train)
knn_reg4.fit(X_train,Y_train)
knn_reg5.fit(X_train,Y_train)
knn_reg35.fit(X_train,Y_train)

KNeighborsRegressor(n_neighbors=35)

In [41]:
# evaluate the performance of the model
# score function
print(knn_reg3.score(X_train,Y_train).round(2))
print(knn_reg4.score(X_train,Y_train).round(2))
print(knn_reg5.score(X_train,Y_train).round(2))
print(knn_reg35.score(X_train,Y_train).round(2))

0.95
0.91
0.87
0.67


In [42]:
print('knn reg3 R2 on train: {:.2%}'.format(knn_reg3.score(X_train,Y_train)))
print('knn reg3 R2 on test: {:.2%}'.format(knn_reg3.score(X_test,Y_test)),'\n')

print('knn reg4 R2 on train: {:.2%}'.format(knn_reg4.score(X_train,Y_train)))
print('knn reg4 R2 on test: {:.2%}'.format(knn_reg4.score(X_test,Y_test)),'\n')

print('knn reg5 R2 on train: {:.2%}'.format(knn_reg5.score(X_train,Y_train)))
print('knn reg5 R2 on test: {:.2%}'.format(knn_reg5.score(X_test,Y_test)),'\n')

print('knn reg35 R2 on train: {:.2%}'.format(knn_reg35.score(X_train,Y_train)))
print('knn reg35 R2 on test: {:.2%}'.format(knn_reg35.score(X_test,Y_test)),'\n')


knn reg3 R2 on train: 94.95%
knn reg3 R2 on test: 96.22% 

knn reg4 R2 on train: 91.08%
knn reg4 R2 on test: 94.22% 

knn reg5 R2 on train: 86.81%
knn reg5 R2 on test: 91.72% 

knn reg35 R2 on train: 66.93%
knn reg35 R2 on test: 74.50% 



In [43]:
#looking for highest test score^
#n_neighbors of 3 gives highest test score

## compare test set performance: validation curve

In [44]:
from sklearn.model_selection import cross_val_score, validation_curve

In [45]:
# cross validation: 
scores10=cross_val_score(knn_reg3, X_test, Y_test,cv=10)
scores9=cross_val_score(knn_reg3,  X_test, Y_test,cv=9)
scores7=cross_val_score(knn_reg3,  X_test, Y_test,cv=7)
scores6=cross_val_score(knn_reg3,  X_test, Y_test,cv=6)
# test scores in each of the folds
print(scores10)
print(scores9)
print(scores7)
print(scores6)

[0.9147091  0.84406019 0.96508581 0.92514411 0.90215565 0.91820892
 0.92061308 0.46497467 0.92691748 0.95081917]
[0.91672907 0.90993453 0.9530434  0.9048698  0.94439995 0.82216316
 0.45607748 0.9306773  0.95032583]
[0.91695082 0.91626229 0.93136552 0.91242981 0.8379903  0.51455074
 0.94219949]
[0.88251203 0.91624761 0.91075096 0.8686503  0.52902186 0.93635392]


## Actual Validation_Curve

In [46]:
#average score across the folds
print('avg R-2 across 10folds: {:.2%}'.format(scores10.mean()))
print('avg R-2 across 9folds: {:.2%}'.format(scores9.mean()))
print('avg R-2 across 7folds: {:.2%}'.format(scores7.mean()))
print('avg R-2 across 6folds: {:.2%}'.format(scores6.mean()))

avg R-2 across 10folds: 87.33%
avg R-2 across 9folds: 86.54%
avg R-2 across 7folds: 85.31%
avg R-2 across 6folds: 84.06%


In [135]:
#Using validation_curve
train_scores, test_scores = validation_curve(KNeighborsRegressor(), X_train, Y_train,
                                                   param_name = "n_neighbors", 
                                                   param_range = [3, 4, 5, 6, 7, 8, 9, 10],
                                                   cv=4)

In [136]:
#Testing and Training Scores - Changed part
print(train_scores.mean(axis=1))
print(test_scores.mean(axis=1))

[0.93008821 0.88022482 0.85234775 0.82814654 0.81301015 0.79614111
 0.78438365 0.7746177 ]
[0.76697969 0.73230253 0.73803532 0.73786761 0.73630694 0.73114098
 0.72795769 0.72373192]


## Validation Curve for this

In [129]:
#Using validation_curve
train_scores, test_scores = validation_curve(KNeighborsRegressor(), X_train, Y_train,
                                                   param_name = "n_neighbors", 
                                                   param_range = [33, 34, 35],
                                                   cv=4)

In [131]:
#Testing and Training Scores - Changed part
print(train_scores.mean(axis=1))
print(test_scores.mean(axis=1))

[0.65087417 0.64824836 0.64498669]
[0.64442388 0.64270082 0.64077798]


## prediction

In [47]:
Y_knn_predictions = knn_reg3.predict(X_test)


In [48]:
Y_knn_predictions

array([31043.33333333, 22528.33333333, 31333.33333333, ...,
       30856.66666667, 33406.66666667, 30225.        ])

In [49]:
Y_test_arr = Y_test.to_numpy()

In [50]:
Y_test_arr


array([33740, 21995, 28380, ..., 32515, 34745, 28520], dtype=int64)

In [51]:
from sklearn.metrics import mean_squared_error

In [52]:
dif = (Y_knn_predictions - Y_test_arr)/Y_test_arr
print('average difference: {:.2%}'.format(dif.mean()))

average difference: 11.95%


# Linear Regression

In [137]:
from sklearn.linear_model import LinearRegression

In [138]:
# define a linear regression
lr=LinearRegression()
# fit (train) the model
lr.fit(X_train,Y_train)

LinearRegression()

In [139]:
# coefficients
lr.coef_.round(2)

array([ 5.28850000e+02,  1.74930000e+02,  1.82895000e+03,  4.82463000e+03,
       -2.47900000e+01,  5.45960000e+02, -1.67200000e+01, -8.33899900e+04,
       -7.46450700e+04,  1.55120300e+04, -3.05613700e+04, -1.71847300e+04,
        7.19987200e+04,  1.61646423e+06, -8.64921100e+04, -5.48551700e+04,
       -6.92643900e+04, -7.49872200e+04, -6.41339100e+04, -7.53118000e+04,
        1.05232080e+05,  1.37497000e+03, -8.25725500e+04, -9.27288600e+04,
       -8.12318900e+04, -5.44591700e+04, -6.82581900e+04, -8.75757100e+04,
       -6.44125000e+04,  1.43644210e+05, -6.58945100e+04, -7.67577500e+04,
       -8.47081000e+04, -5.08182800e+04, -4.20991100e+04,  3.82681330e+05,
       -7.87019500e+04,  3.69920400e+04, -6.49403600e+04, -8.10658800e+04,
       -6.09085700e+04, -8.95600200e+04, -8.21564500e+04, -8.69802900e+04,
       -2.89896300e+04,  1.64144290e+05, -8.16206800e+04, -8.85683300e+04,
        5.83285500e+04, -7.91475400e+04, -7.79051900e+04, -6.54010000e+03,
       -5.90842700e+04, -

In [140]:
# intercept of the linear regression
lr.intercept_.round(2)

-1020240.12

In [141]:
# evaluate the performance
print('lr R2 on train: {:.2%}'.format(lr.score(X_train,Y_train)))
print('lr R2 on test: {:.2%}'.format(lr.score(X_test,Y_test)))


lr R2 on train: 82.61%
lr R2 on test: 88.83%


## Validation Curve on Linear Regression

In [58]:
# not better than Knn 

## compare test set performance: validation curve

In [59]:
# cross validation: 
scores10=cross_val_score(lr, X_test, Y_test,cv=10)
scores9=cross_val_score(lr,  X_test, Y_test,cv=9)
scores7=cross_val_score(lr,  X_test, Y_test,cv=7)
scores6=cross_val_score(lr,  X_test, Y_test,cv=6)
# test scores in each of the folds
print(scores10)
print(scores9)
print(scores7)
print(scores6)

[0.83151567 0.83501071 0.91145671 0.91901783 0.91783419 0.87608755
 0.82029796 0.36145375 0.84643004 0.89249359]
[0.83269072 0.90944892 0.83213988 0.93152913 0.89754045 0.81111806
 0.35979098 0.86415874 0.87017244]
[0.8196145  0.88773212 0.92335829 0.8976442  0.82019144 0.41724184
 0.8697238 ]
[0.79708831 0.89065469 0.92883543 0.84952096 0.42970864 0.86892652]


In [60]:
#average score across the folds
print('avg R-2 across 10folds: {:.2%}'.format(scores10.mean()))
print('avg R-2 across 9folds: {:.2%}'.format(scores9.mean()))
print('avg R-2 across 7folds: {:.2%}'.format(scores7.mean()))
print('avg R-2 across 6folds: {:.2%}'.format(scores6.mean()))

avg R-2 across 10folds: 82.12%
avg R-2 across 9folds: 81.21%
avg R-2 across 7folds: 80.51%
avg R-2 across 6folds: 79.41%


In [61]:
#not better than Knn

## prediction

In [62]:
Y_lr_predictions = lr.predict(X_test)


In [63]:
dif = (Y_lr_predictions - Y_test_arr)/Y_test_arr
print('average difference: {:.2%}'.format(dif.mean()))

average difference: 25.28%


In [64]:
#greater difference than Knn

# Lasso

In [65]:
from sklearn.linear_model import Lasso

In [66]:
# defining a Lasso model
lasso=Lasso()
# fit the model
lasso.fit(X_train, Y_train)

C:\Users\jchac_vjlwe8u\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.670e+11, tolerance: 3.411e+09
  model = cd_fast.enet_coordinate_descent(


Lasso()

In [67]:
# evaluating the performance
print('lasso R2 on train: {:.2%}'.format(lasso.score(X_train,Y_train)))
print('lasso R2 on test: {:.2%}'.format(lasso.score(X_test,Y_test)))
print('lasso # of non-zero coffs:',sum(lasso.coef_!=0),'\n')

lasso R2 on train: 82.61%
lasso R2 on test: 88.87%
lasso # of non-zero coffs: 86 



In [68]:
#not better than Knn

## compare test set performance: validation curve

In [69]:
# cross validation: 
scores10=cross_val_score(lasso, X_test, Y_test,cv=10)
scores9=cross_val_score(lasso,  X_test, Y_test,cv=9)
scores7=cross_val_score(lasso,  X_test, Y_test,cv=7)
scores6=cross_val_score(lasso,  X_test, Y_test,cv=6)
# test scores in each of the folds
print(scores10)
print(scores9)
print(scores7)
print(scores6)

C:\Users\jchac_vjlwe8u\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.517e+11, tolerance: 7.190e+08
  model = cd_fast.enet_coordinate_descent(
C:\Users\jchac_vjlwe8u\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.922e+09, tolerance: 5.202e+08
  model = cd_fast.enet_coordinate_descent(


[0.8315049  0.83506563 0.91181088 0.91885958 0.91768546 0.87627729
 0.82073024 0.32353966 0.84652521 0.89232399]
[0.83256771 0.9099144  0.83226781 0.93134542 0.89728126 0.81188182
 0.32307691 0.85018422 0.87011062]
[0.8195512  0.88808048 0.92326927 0.89757218 0.82062592 0.38333881
 0.86960758]
[0.79709432 0.89096858 0.92860733 0.84997263 0.39736701 0.86885101]


In [70]:
#average score across the folds
print('avg R-2 across 10folds: {:.2%}'.format(scores10.mean()))
print('avg R-2 across 9folds: {:.2%}'.format(scores9.mean()))
print('avg R-2 across 7folds: {:.2%}'.format(scores7.mean()))
print('avg R-2 across 6folds: {:.2%}'.format(scores6.mean()))

avg R-2 across 10folds: 81.74%
avg R-2 across 9folds: 80.65%
avg R-2 across 7folds: 80.03%
avg R-2 across 6folds: 78.88%


In [71]:
#not better than Knn

## Validation Curve for Lasso

In [149]:
#Using validation_curve
train_scores, test_scores = validation_curve(Lasso(), X_train, Y_train,
                                                   param_name = "alpha", 
                                                   param_range = [0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
                                                   cv=4)

C:\Users\jchac_vjlwe8u\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.301e+12, tolerance: 2.820e+09
  model = cd_fast.enet_coordinate_descent(
C:\Users\jchac_vjlwe8u\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.015e+12, tolerance: 2.820e+09
  model = cd_fast.enet_coordinate_descent(
C:\Users\jchac_vjlwe8u\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality 

In [150]:
print(train_scores.mean(axis=1))
print(test_scores.mean(axis=1))

[0.82465563 0.82465486 0.82465386 0.82465268 0.82465131 0.82464973]
[0.67712602 0.6771031  0.67709598 0.67709025 0.6770879  0.67708516]


## prediction

In [72]:
Y_lasso_predictions = lasso.predict(X_test)


In [73]:
dif = (Y_lasso_predictions - Y_test_arr)/Y_test_arr
print('average difference: {:.2%}'.format(dif.mean()))

average difference: 25.18%


In [74]:
#greater difference than Knn but less than Lr

# Ridge

In [75]:
from sklearn.linear_model import Ridge

In [76]:
# define a Ridge model
ridge=Ridge()
# fit (train) the model
ridge.fit(X_train, Y_train)

Ridge()

In [77]:
# ridge model coefficients
ridge.coef_.round(2)

array([ 4.12160000e+02,  1.98140000e+02,  2.79220000e+03,  4.33472000e+03,
       -7.60000000e-01,  6.49880000e+02, -1.48300000e+01, -6.81599300e+04,
       -4.91586800e+04,  2.11515300e+04, -2.31762300e+04, -1.05221600e+04,
        7.79472700e+04,  1.06572218e+06, -6.95823300e+04, -4.32000200e+04,
       -5.58003600e+04, -6.01230600e+04, -5.20032100e+04, -5.68149600e+04,
        1.02515130e+05,  6.86780000e+03, -6.73088900e+04, -5.80623300e+04,
       -6.05464500e+04, -4.17222700e+04, -5.43727800e+04, -7.25768300e+04,
       -5.10781200e+04,  1.38113420e+05, -5.02651100e+04, -6.26380200e+04,
       -6.87663700e+04, -3.45812100e+04, -2.99817100e+04,  3.60076920e+05,
       -6.26513700e+04,  3.06361600e+04, -5.34821900e+04, -6.43810500e+04,
       -4.85703100e+04, -7.29619900e+04, -6.54792800e+04, -7.10877600e+04,
       -2.11416100e+04,  1.64896940e+05, -6.51518200e+04, -6.98010000e+04,
        4.58527400e+04, -6.32191400e+04, -6.13072400e+04,  1.05851100e+04,
       -4.64583300e+04, -

In [78]:
# number of coefs in ridge that have smaller absolute value compared to lr
sum(abs(ridge.coef_)<=abs(lr.coef_))

64

In [79]:
# assess ridge's performance
print('ridge R2 on train: {:.2%}'.format(ridge.score(X_train, Y_train)))
print('ridge R2 on test: {:.2%}'.format(ridge.score(X_test, Y_test)))

ridge R2 on train: 80.77%
ridge R2 on test: 90.41%


In [80]:
# not better than Knn

In [81]:
#test different alphas
# smaller alpha--- more complex model, higher chance of over-fitting
# larger alpha-- less complex (simpler)n model, lower chance of over-fitting
### but, if we keep increasing alpha, model might become too simple,
### and we could have under-fitting
ridge1=Ridge(alpha=.3)
ridge2=Ridge(alpha=.5)
ridge3=Ridge(alpha=.8)

In [82]:
# fit the model
ridge1.fit(X_train, Y_train)
ridge2.fit(X_train, Y_train)
ridge3.fit(X_train, Y_train)

Ridge(alpha=0.8)

In [83]:
print('ridge1 R2 on train: {:.2%}'.format(ridge1.score(X_train, Y_train)))
print('ridge1 R2 on test: {:.2%}'.format(ridge1.score(X_test, Y_test)),'\n')

print('ridge2 R2 on train: {:.2%}'.format(ridge2.score(X_train, Y_train)))
print('ridge2 R2 on test: {:.2%}'.format(ridge2.score(X_test, Y_test)),'\n')

print('ridge3 R2 on train: {:.2%}'.format(ridge3.score(X_train, Y_train)))
print('ridge3 R2 on test: {:.2%}'.format(ridge3.score(X_test, Y_test)),'\n')

ridge1 R2 on train: 82.33%
ridge1 R2 on test: 90.30% 

ridge2 R2 on train: 81.95%
ridge2 R2 on test: 90.63% 

ridge3 R2 on train: 81.26%
ridge3 R2 on test: 90.62% 



In [84]:
#FINAL: best test score is with an alpha of .5

## compare test set performance: validation curve

In [85]:
# cross validation:
scores10=cross_val_score(ridge2, X_test, Y_test,cv=10)
scores9=cross_val_score(ridge2,  X_test, Y_test,cv=9)
scores7=cross_val_score(ridge2,  X_test, Y_test,cv=7)
scores6=cross_val_score(ridge2,  X_test, Y_test,cv=6)
# test scores in each of the folds
print(scores10)
print(scores9)
print(scores7)
print(scores6)

[0.81414418 0.82525798 0.90477661 0.90589711 0.90535092 0.87843266
 0.83183449 0.3715804  0.8410645  0.87526497]
[0.81197859 0.90583722 0.82578984 0.91760511 0.8931666  0.82310332
 0.36970737 0.85791992 0.86019717]
[0.80104229 0.88160128 0.90910539 0.89685887 0.81971586 0.42753465
 0.85776592]
[0.7788284  0.88547352 0.91186205 0.86055627 0.43937636 0.85631461]


In [86]:
#average score across the folds
print('avg R-2 across 10folds: {:.2%}'.format(scores10.mean()))
print('avg R-2 across 9folds: {:.2%}'.format(scores9.mean()))
print('avg R-2 across 7folds: {:.2%}'.format(scores7.mean()))
print('avg R-2 across 6folds: {:.2%}'.format(scores6.mean()))

avg R-2 across 10folds: 81.54%
avg R-2 across 9folds: 80.73%
avg R-2 across 7folds: 79.91%
avg R-2 across 6folds: 78.87%


In [87]:
#not better than Knn

## Validation Curve on Ridge

In [142]:
#Using validation_curve
train_scores, test_scores = validation_curve(Ridge(), X_train, Y_train,
                                                   param_name = "alpha", 
                                                   param_range = [0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
                                                   cv=4)

In [143]:
print(train_scores.mean(axis=1))
print(test_scores.mean(axis=1))

[0.82186672 0.82010513 0.81810564 0.81593672 0.81365042 0.81128645]
[0.68383657 0.68381422 0.683733   0.68360345 0.68343375 0.68323035]


## prediction

In [88]:
Y_ridge_predictions = ridge2.predict(X_test)


In [89]:
dif = (Y_ridge_predictions - Y_test_arr)/Y_test_arr
print('average difference: {:.2%}'.format(dif.mean()))

average difference: 26.20%


In [90]:
#greater difference than all thus far

# Decision tree

In [91]:
#use shuffled data
Car_Sh=car_dummies.sample(frac=1, random_state=0)
Car_Sh.head(2)


MSRP  Year  Engine HP  Engine Cylinders  Number of Doors  highway MPG  \
9421  33740  2003      185.0               6.0              4.0           24   
5871  21995  2015      148.0               4.0              4.0           36   

      city mpg  Popularity  Make_Acura  Make_Alfa Romeo  ...  \
9421        17          26           0                0  ...   
5871        27         640           0                0  ...   

      Vehicle Style_Convertible  Vehicle Style_Convertible SUV  \
9421                          0                              0   
5871                          0                              0   

      Vehicle Style_Coupe  Vehicle Style_Crew Cab Pickup  \
9421                    0                              0   
5871                    0                              0   

      Vehicle Style_Extended Cab Pickup  Vehicle Style_Passenger Minivan  \
9421                                  0                                1   
5871                                  0                                0   

      Vehicle Style_Passenger Van  Vehicle Style_Regular Cab Pickup  \
9421                            0                                 0   
5871                            0                                 0   

      Vehicle Style_Sedan  Vehicle Style_Wagon  
9421                    0                    0  
5871                    0                    0  

[2 rows x 94 columns]

In [92]:
# create features and target sets 
X_Sh_Car, Y_Sh_Car=Car_Sh.iloc[:,1:], Car_Sh['MSRP']
# check my work
display(X_Sh_Car.head(1))
display(Y_Sh_Car.head(1))

Year  Engine HP  Engine Cylinders  Number of Doors  highway MPG  \
9421  2003      185.0               6.0              4.0           24   

      city mpg  Popularity  Make_Acura  Make_Alfa Romeo  Make_Aston Martin  \
9421        17          26           0                0                  0   

      ...  Vehicle Style_Convertible  Vehicle Style_Convertible SUV  \
9421  ...                          0                              0   

      Vehicle Style_Coupe  Vehicle Style_Crew Cab Pickup  \
9421                    0                              0   

      Vehicle Style_Extended Cab Pickup  Vehicle Style_Passenger Minivan  \
9421                                  0                                1   

      Vehicle Style_Passenger Van  Vehicle Style_Regular Cab Pickup  \
9421                            0                                 0   

      Vehicle Style_Sedan  Vehicle Style_Wagon  
9421                    0                    0  

[1 rows x 93 columns]

9421    33740
Name: MSRP, dtype: int64

In [93]:
Xs_train, Xs_test, Ys_train, Ys_test=train_test_split(X_Sh_Car,Y_Sh_Car,
                                                 test_size=.2,
                                                 random_state=0)

In [94]:
from sklearn.tree import DecisionTreeRegressor, export_graphviz

## Validation Curve for the Decision Tree

In [95]:
train_scores, test_scores=validation_curve(
    DecisionTreeRegressor(random_state=0),Xs_train,Ys_train,
param_name='max_depth',param_range=[5,6,7,8],cv=5)

In [96]:
train_scores.mean(axis=1).round(3)

array([0.922, 0.945, 0.959, 0.97 ])

In [97]:
test_scores.mean(axis=1).round(3)
# max_depth 8 is the best value

array([0.686, 0.718, 0.739, 0.751])

In [98]:
# define and fit the model
dt_reg=DecisionTreeRegressor(random_state=0,max_depth=8)
dt_reg.fit(Xs_train,Ys_train)

DecisionTreeRegressor(max_depth=8, random_state=0)

In [99]:
print('dt_reg on train: {:.2%}'.format(dt_reg.score(Xs_train, Ys_train)))
print('dt_reg on test: {:.2%}'.format(dt_reg.score(Xs_test, Ys_test)))

dt_reg on train: 96.53%
dt_reg on test: 80.37%


In [100]:
feat_imp1=pd.DataFrame(data=dt_reg.feature_importances_.round(3),
                      index=Xs_train.columns,columns=['importance'])
feat_imp1.sort_values('importance',ascending=False)

importance
Engine Cylinders                                         0.591
Engine HP                                                0.175
Year                                                     0.058
Vehicle Style_Sedan                                      0.045
Make_Maybach                                             0.038
highway MPG                                              0.027
Make_Rolls-Royce                                         0.012
Engine Fuel Type_regular unleaded                        0.012
Make_Bentley                                             0.008
Popularity                                               0.006
Transmission Type_AUTOMATED_MANUAL                       0.006
city mpg                                                 0.004
Make_Lamborghini                                         0.003
Engine Fuel Type_premium unleaded (recommended)          0.003
Vehicle Size_Compact                                     0.003
Make_Ferrari                                             0.002
Make_Tesla                                               0.001
Engine Fuel Type_diesel                                  0.001
Vehicle Style_4dr SUV                                    0.001
Engine Fuel Type_premium unleaded (required)             0.001
Driven_Wheels_all wheel drive                            0.001
Number of Doors                                          0.001
Make_Nissan                                              0.001
Vehicle Style_Convertible SUV                            0.000
Engine Fuel Type_natural gas                             0.000
Vehicle Style_Passenger Minivan                          0.000
Vehicle Style_Passenger Van                              0.000
Vehicle Style_Regular Cab Pickup                         0.000
Engine Fuel Type_flex-fuel (unleaded/natural gas)        0.000
Engine Fuel Type_flex-fuel (unleaded/E85)                0.000
Transmission Type_AUTOMATIC                              0.000
Engine Fuel Type_flex-fuel (premium unleaded re...       0.000
Engine Fuel Type_flex-fuel (premium unleaded re...       0.000
Engine Fuel Type_electric                                0.000
Vehicle Style_Extended Cab Pickup                        0.000
Transmission Type_DIRECT_DRIVE                           0.000
Vehicle Style_Crew Cab Pickup                            0.000
Vehicle Size_Large                                       0.000
Vehicle Style_Cargo Van                                  0.000
Vehicle Style_Cargo Minivan                              0.000
Vehicle Style_4dr Hatchback                              0.000
Vehicle Style_2dr SUV                                    0.000
Vehicle Style_2dr Hatchback                              0.000
Vehicle Size_Midsize                                     0.000
Make_Volkswagen                                          0.000
Vehicle Style_Convertible                                0.000
Driven_Wheels_rear wheel drive                           0.000
Driven_Wheels_front wheel drive                          0.000
Vehicle Style_Coupe                                      0.000
Driven_Wheels_four wheel drive                           0.000
Transmission Type_UNKNOWN                                0.000
Transmission Type_MANUAL                                 0.000
Make_Volvo                                               0.000
Make_Saab                                                0.000
Make_Toyota                                              0.000
Make_Chevrolet                                           0.000
Make_HUMMER                                              0.000
Make_Genesis                                             0.000
Make_GMC                                                 0.000
Make_Ford                                                0.000
Make_FIAT                                                0.000
Make_Dodge                                               0.000
Make_Chrysler                                            0.000
Make_Cadillac       

## compare test set performance: validation curve

In [101]:
# cross validation: 
scores10=cross_val_score(dt_reg, X_test, Y_test,cv=10)
scores9=cross_val_score(dt_reg,  X_test, Y_test,cv=9)
scores7=cross_val_score(dt_reg,  X_test, Y_test,cv=7)
scores6=cross_val_score(dt_reg,  X_test, Y_test,cv=6)
# test scores in each of the folds
print(scores10)
print(scores9)
print(scores7)
print(scores6)

[0.79844878 0.83606987 0.96484968 0.90155164 0.73406048 0.93239411
 0.9194637  0.50702646 0.94361279 0.92126652]
[0.78077912 0.91247713 0.88906083 0.93476973 0.77878797 0.93520324
 0.50419519 0.93792467 0.94021558]
[0.7524637  0.87316797 0.92167088 0.85012522 0.91591078 0.42338333
 0.94477612]
[0.74110965 0.96310308 0.88193383 0.929438   0.55362254 0.94005915]


In [102]:
#average score across the folds
print('avg R-2 across 10folds: {:.2%}'.format(scores10.mean()))
print('avg R-2 across 9folds: {:.2%}'.format(scores9.mean()))
print('avg R-2 across 7folds: {:.2%}'.format(scores7.mean()))
print('avg R-2 across 6folds: {:.2%}'.format(scores6.mean()))

avg R-2 across 10folds: 84.59%
avg R-2 across 9folds: 84.59%
avg R-2 across 7folds: 81.16%
avg R-2 across 6folds: 83.49%


In [103]:
#not better than Knn

## prediction

In [104]:
Y_dt_reg_predictions = dt_reg.predict(X_test)


In [105]:
dif = (Y_dt_reg_predictions - Y_test_arr)/Y_test_arr
print('average difference: {:.2%}'.format(dif.mean()))

average difference: 3.37%


In [106]:
#greatest results than all thus far

### Visualization

In [107]:
export_graphviz(dt_reg,out_file='reg_tree1.dot',
                feature_names=Xs_train.columns,filled=True)

In [108]:
#http://webgraphviz.com/

# Random Forest Regressor

In [109]:
from sklearn.ensemble import RandomForestRegressor

In [110]:
dt_rand = RandomForestRegressor(random_state=0,n_estimators=100)

In [111]:
dt_rand.fit(Xs_train, Ys_train)

RandomForestRegressor(random_state=0)

In [112]:
print('Decision tree acc on train: {:.3%}'.format(dt_rand.score(Xs_train, Ys_train)))
print('Decision tree acc on test: {:.3%}'.format(dt_rand.score(Xs_test, Ys_test)))

Decision tree acc on train: 98.512%
Decision tree acc on test: 98.347%


In [113]:
feat_imp2=pd.DataFrame(data=dt_rand.feature_importances_.round(3),
                      index=Xs_train.columns,columns=['importance'])
feat_imp2.sort_values('importance',ascending=False)

importance
Engine HP                                                0.410
Engine Cylinders                                         0.290
Make_Bugatti                                             0.063
city mpg                                                 0.039
Popularity                                               0.035
Year                                                     0.034
Vehicle Style_Convertible                                0.024
highway MPG                                              0.021
Make_Maybach                                             0.012
Vehicle Style_Sedan                                      0.010
Make_Bentley                                             0.009
Vehicle Size_Compact                                     0.006
Make_Rolls-Royce                                         0.006
Make_Lamborghini                                         0.005
Transmission Type_AUTOMATED_MANUAL                       0.005
Engine Fuel Type_premium unleaded (required)             0.003
Vehicle Size_Midsize                                     0.003
Make_Dodge                                               0.002
Engine Fuel Type_premium unleaded (recommended)          0.002
Number of Doors                                          0.002
Engine Fuel Type_regular unleaded                        0.001
Make_Porsche                                             0.001
Driven_Wheels_rear wheel drive                           0.001
Driven_Wheels_all wheel drive                            0.001
Vehicle Size_Large                                       0.001
Engine Fuel Type_diesel                                  0.001
Transmission Type_MANUAL                                 0.001
Vehicle Style_4dr SUV                                    0.001
Make_Ferrari                                             0.001
Transmission Type_AUTOMATIC                              0.001
Vehicle Style_Coupe                                      0.001
Make_Cadillac                                            0.001
Make_Tesla                                               0.001
Make_Audi                                                0.001
Engine Fuel Type_flex-fuel (unleaded/natural gas)        0.000
Engine Fuel Type_flex-fuel (unleaded/E85)                0.000
Engine Fuel Type_flex-fuel (premium unleaded re...       0.000
Engine Fuel Type_flex-fuel (premium unleaded re...       0.000
Engine Fuel Type_natural gas                             0.000
Vehicle Style_2dr Hatchback                              0.000
Transmission Type_DIRECT_DRIVE                           0.000
Transmission Type_UNKNOWN                                0.000
Driven_Wheels_four wheel drive                           0.000
Driven_Wheels_front wheel drive                          0.000
Vehicle Style_2dr SUV                                    0.000
Vehicle Style_4dr Hatchback                              0.000
Vehicle Style_Cargo Minivan                              0.000
Vehicle Style_Cargo Van                                  0.000
Vehicle Style_Convertible SUV                            0.000
Vehicle Style_Crew Cab Pickup                            0.000
Vehicle Style_Extended Cab Pickup                        0.000
Vehicle Style_Passenger Minivan                          0.000
Vehicle Style_Passenger Van                              0.000
Vehicle Style_Regular Cab Pickup                         0.000
Engine Fuel Type_electric                                0.000
Make_Saab                                                0.000
Make_Volvo                                               0.000
Make_Land Rover                                          0.000
Make_Infiniti                                            0.000
Make_Hyundai                                             0.000
Make_Honda                                               0.000
Make_HUMMER                                              0.000
Make_Genesis                                             0.000
Make_GMC            

In [114]:
pd.options.display.max_rows = 100000

In [115]:
feat_imp2=pd.DataFrame(data=dt_rand.feature_importances_.round(3),
                      index=Xs_train.columns,columns=['importance'])
feat_imp2.sort_values('importance',ascending=False)

importance
Engine HP                                                0.410
Engine Cylinders                                         0.290
Make_Bugatti                                             0.063
city mpg                                                 0.039
Popularity                                               0.035
Year                                                     0.034
Vehicle Style_Convertible                                0.024
highway MPG                                              0.021
Make_Maybach                                             0.012
Vehicle Style_Sedan                                      0.010
Make_Bentley                                             0.009
Vehicle Size_Compact                                     0.006
Make_Rolls-Royce                                         0.006
Make_Lamborghini                                         0.005
Transmission Type_AUTOMATED_MANUAL                       0.005
Engine Fuel Type_premium unleaded (required)             0.003
Vehicle Size_Midsize                                     0.003
Make_Dodge                                               0.002
Engine Fuel Type_premium unleaded (recommended)          0.002
Number of Doors                                          0.002
Engine Fuel Type_regular unleaded                        0.001
Make_Porsche                                             0.001
Driven_Wheels_rear wheel drive                           0.001
Driven_Wheels_all wheel drive                            0.001
Vehicle Size_Large                                       0.001
Engine Fuel Type_diesel                                  0.001
Transmission Type_MANUAL                                 0.001
Vehicle Style_4dr SUV                                    0.001
Make_Ferrari                                             0.001
Transmission Type_AUTOMATIC                              0.001
Vehicle Style_Coupe                                      0.001
Make_Cadillac                                            0.001
Make_Tesla                                               0.001
Make_Audi                                                0.001
Engine Fuel Type_flex-fuel (unleaded/natural gas)        0.000
Engine Fuel Type_flex-fuel (unleaded/E85)                0.000
Engine Fuel Type_flex-fuel (premium unleaded re...       0.000
Engine Fuel Type_flex-fuel (premium unleaded re...       0.000
Engine Fuel Type_natural gas                             0.000
Vehicle Style_2dr Hatchback                              0.000
Transmission Type_DIRECT_DRIVE                           0.000
Transmission Type_UNKNOWN                                0.000
Driven_Wheels_four wheel drive                           0.000
Driven_Wheels_front wheel drive                          0.000
Vehicle Style_2dr SUV                                    0.000
Vehicle Style_4dr Hatchback                              0.000
Vehicle Style_Cargo Minivan                              0.000
Vehicle Style_Cargo Van                                  0.000
Vehicle Style_Convertible SUV                            0.000
Vehicle Style_Crew Cab Pickup                            0.000
Vehicle Style_Extended Cab Pickup                        0.000
Vehicle Style_Passenger Minivan                          0.000
Vehicle Style_Passenger Van                              0.000
Vehicle Style_Regular Cab Pickup                         0.000
Engine Fuel Type_electric                                0.000
Make_Saab                                                0.000
Make_Volvo                                               0.000
Make_Land Rover                                          0.000
Make_Infiniti                                            0.000
Make_Hyundai                                             0.000
Make_Honda                                               0.000
Make_HUMMER                                              0.000
Make_Genesis                                             0.000
Make_GMC            

## compare test set performance: validation curve

In [116]:
# cross validation:
scores10=cross_val_score(dt_rand, Xs_test, Ys_test,cv=10)
scores9=cross_val_score(dt_rand,  Xs_test, Ys_test,cv=9)
scores7=cross_val_score(dt_rand,  Xs_test, Ys_test,cv=7)
scores6=cross_val_score(dt_rand,  Xs_test, Ys_test,cv=6)
# test scores in each of the folds
print(scores10)
print(scores9)
print(scores7)
print(scores6)

[0.95789205 0.96105124 0.9536329  0.93950873 0.9314176  0.95821435
 0.85676257 0.79275484 0.9685112  0.91353025]
[0.96106921 0.95544148 0.94694149 0.95064414 0.96762744 0.86010365
 0.8471539  0.96512705 0.91983594]
[0.95543401 0.94082818 0.93411679 0.97036455 0.88225069 0.79039519
 0.92930979]
[0.95514858 0.94004    0.93094934 0.88899715 0.86675501 0.92654481]


In [117]:
#average score across the folds
print('avg R-2 across 10folds: {:.2%}'.format(scores10.mean()))
print('avg R-2 across 9folds: {:.2%}'.format(scores9.mean()))
print('avg R-2 across 7folds: {:.2%}'.format(scores7.mean()))
print('avg R-2 across 6folds: {:.2%}'.format(scores6.mean()))

avg R-2 across 10folds: 92.33%
avg R-2 across 9folds: 93.04%
avg R-2 across 7folds: 91.47%
avg R-2 across 6folds: 91.81%


In [118]:
# better than Knn

## prediction

In [119]:
Y_dt_rand_predictions = dt_rand.predict(X_test)


In [120]:
dif = (Y_dt_rand_predictions - Y_test_arr)/Y_test_arr
print('average difference: {:.2%}'.format(dif.mean()))

average difference: 1.04%


In [121]:
#greatest results than all thus far


In [122]:
results = pd.DataFrame(Y_dt_rand_predictions.round(), columns=['predictions'])
results['actual']=Y_test_arr.tolist()
results['difference']= ((results['predictions']- results['actual'])/results['actual']).round(3)

In [123]:
results

predictions   actual  difference
0         31216.0    33740      -0.075
1         21054.0    21995      -0.043
2         31430.0    28380       0.107
3         31302.0    32300      -0.031
4         36058.0    34150       0.056
5         18656.0    18370       0.016
6         26714.0    25165       0.062
7         12746.0    12340       0.033
8         27499.0    27045       0.017
9          2012.0     2000       0.006
10        33858.0    32550       0.040
11        34146.0    32030       0.066
12        18695.0    18250       0.024
13        20401.0    19365       0.053
14        39733.0    45815      -0.133
15        27737.0    29945      -0.074
16        29680.0    33595      -0.117
17        21939.0    22595      -0.029
18        33485.0    29155       0.149
19        16183.0    16100       0.005
20        21287.0    21270       0.001
21        41938.0    42075      -0.003
22        36167.0    37240      -0.029
23        29534.0    34195      -0.136
24        33886.0    31905       0.062
25        35205.0    32850       0.072
26        24083.0    23400       0.029
27        37771.0    37000       0.021
28        27623.0    25865       0.068
29        20895.0    19975       0.046
30        23988.0    20695       0.159
31        23938.0    23055       0.038
32         2146.0     2124       0.010
33        33957.0    28700       0.183
34        20493.0    20080       0.021
35        32140.0    32300      -0.005
36        12810.0    13485      -0.050
37        39465.0    40450      -0.024
38       228865.0   230900      -0.009
39        31302.0    28300       0.106
40        26685.0    25850       0.032
41        21758.0    22595      -0.037
42        15389.0    14199       0.084
43       226109.0   225400       0.003
44         2661.0     2590       0.027
45        26628.0    26299       0.013
46        30813.0    33230      -0.073
47        14293.0    14165       0.009
48        27890.0    27740       0.005
49         2000.0     2000       0.000
50        52777.0    42300       0.248
51        40905.0    42390      -0.035
52        17859.0    18515      -0.035
53        54443.0    56555      -0.037
54        28501.0    29300      -0.027
55        45042.0    47155      -0.045
56        29580.0    29905      -0.011
57         2813.0     3044      -0.076
58        25342.0    25799      -0.018
59        41846.0    38100       0.098
60        35397.0    31200       0.135
61        20209.0    20045       0.008
62        28726.0    25695       0.118
63        28219.0    27185       0.038
64        41527.0    39970       0.039
65        21032.0    20275       0.037
66        27339.0    28365      -0.036
67        28936.0    28279       0.023
68        31797.0    31125       0.022
69        21441.0    21995      -0.025
70         3403.0     3223       0.056
71        36058.0    36800      -0.020
72        33526.0    32730       0.024
73         2044.0     2000       0.022
74        85930.0    75995       0.131
75        24636.0    23995       0.027
76        58197.0    59700      -0.025
77        16592.0    17850      -0.070
78        15064.0    14895       0.011
79        40235.0    46530      -0.135
80        25237.0    24180       0.044
81        17483.0    17475       0.000
82        51076.0    50580       0.010
83        31219.0    36931      -0.155
84         2378.0     2242       0.061
85        23697.0    23600       0.004
86        27799.0    27000       0.030
87        73594.0    68340       0.077
88       217642.0   235307      -0.075
89        54037.0    50950       0.061
90        36371.0    41720      -0.128
91        48296.0    54540      -0.114
92        15166.0    15349      -0.012
93        25397.0    23649       0.074
94        28218.0    30135      -0.064
95         2000.0     2000       0.000
96        85524.0    84950       0.007
97        27047.0    25997       0.040
98        40091.0    37450       0.071
99        30675.0    32600      -0.059
100        5611.0     5860      -0.042
101       41816.0    40190  

In [124]:
#all code written by Olivia M. Forrester

## Validation curve for Random Forest

In [151]:
train_scores, test_scores = validation_curve(RandomForestRegressor(random_state = 0), Xs_train, Ys_train,
                                                   param_name = "max_depth", 
                                                   param_range = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                                                   cv=4)

In [152]:
#Finding the accuracy scores of the testing and training data
print(train_scores.mean(axis=1))
print(test_scores.mean(axis=1))

[0.51388721 0.7228499  0.8272125  0.89184723 0.93071001 0.95031088
 0.96158421 0.96800734 0.97221935 0.97505275]
[0.43626291 0.56384381 0.67775444 0.75550416 0.814195   0.83786457
 0.84755589 0.85565377 0.86914968 0.8666844 ]
